# Generated by Django 4.2.4 on 2023-09-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.IntegerField()),
                ('css', models.IntegerField()),
                ('javascript', models.IntegerField()),
                ('react', models.IntegerField()),
                ('express', models.IntegerField()),
                ('Cprogram', models.IntegerField()),
                ('Cplus', models.IntegerField()),
                ('CSharp', models.IntegerField()),
                ('asp_dotnet_core', models.IntegerField()),
            ],
        ),
    ]
